### ISSUE TITLE
sha1 not working

### ISSUE THREAD

**Issue by shariat1** [CiKu370/hasher#4]
sha1 was not working so fix it.....this tool is very first...and nice...

**Comment by ghost** [comment]
If this is the issue:
Traceback (most recent call last):
  File "hash.py", line 584, in <module>
    hash()
  File "hash.py", line 319, in hash
    print (B+"["+W+"{}"+B+"]"+G+" password not found\n").format(date)
NameError: global name 'date' is not defined
Just go to line 319 and you can see the error date is not defined and change from format(date) to format(time) and it will work.
